"""Render predictions.md from tpprof.model.predictions(). Deterministic: no timestamps."""
from __future__ import annotations

import argparse
import pathlib

from tpprof import model

SETS = ("central", "optimistic", "pessimistic")
HYPOTHESES = (          # (row label, predictions() band key, statement, kind)
    ("H1", "H1", "TP2 decode step speedup over TP1 at batch 1, context 1216", "ratio"),
    ("H2", "H2", "Rise in TP2 decode scaling efficiency e = speedup / 2 from batch 1 to batch 128: e(128) - e(1)",
     "ratio"),
    ("H2 (prefill)", "H2_prefill",
     "Rise in TP2 prefill scaling efficiency e = speedup / 2 from 512 to 8192 prompt tokens: e(8192) - e(512)",
     "ratio"),
    ("H3", "H3", "DP2 / TP2 saturation output throughput (1024 in / 256 out, no-preemption bound)", "ratio"),
    ("H4", "H4", "Goodput crossover s* (TPOT SLO, ms; TTFT SLO 1 s): TP2 wins below it, DP2 above", "ms"),
    ("H5", "H5", "TP2 / TP1 KV cache capacity, tokens per engine", "ratio"),
    ("H8", "H8", "AR3 (pure NCCL, unfused residual+RMSNorm) / default fused path, TP2 decode step at batch 1",
     "ratio"),
)
CONSTANT_UNITS = {
    "bw_eff": "B/s", "gemm_flops": "FLOP/s", "attn_flops": "FLOP/s", "t_fixed": "s", "t_extra_tp2": "s",
    "alpha": "s", "beta": "B/s", "alpha_nccl_graph": "s", "unfused_norm_s": "s", "ag_alpha": "s",
    "ew_bytes_tp1": "B/token/layer", "ew_bytes_tp2": "B/token/layer", "total_mem_gib": "GiB",
    "gpu_mem_util": "fraction", "weights_gib_tp1": "GiB", "weights_gib_tp2": "GiB",
    "nonkv_gib_tp1": "GiB", "nonkv_gib_tp2": "GiB",
}


def _ms(x: float) -> str:
    """Two decimals, as the brief asks, but never more digits than the 4 significant ones
    predictions() keeps: 5.85 -> "5.85", 223.6 -> "223.6" (not "223.60"), 1234 -> "1234"."""
    int_digits = len(str(int(abs(x))))
    return f"{x:.{max(0, min(2, 4 - int_digits))}f}"


def _count(x: float) -> str:
    return f"{x:,.0f}"


def _ratio(x: float) -> str:
    return f"{x:.3f}"


def _hyp_value(x: float | None, kind: str) -> str:
    if x is None:
        return "none"
    return _ms(x) if kind == "ms" else _ratio(x)


def _table(header: list[str], rows: list[list[str]]) -> list[str]:
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    lines += ["| " + " | ".join(r) + " |" for r in rows]
    return lines


def _tp_tables(section: dict, speedups: dict, key_label: str) -> list[str]:
    lines: list[str] = []
    for name in SETS:
        tp1, tp2, sp = section[name]["1"], section[name]["2"], speedups[name]
        rows = [[k, _ms(tp1[k]), _ms(tp2[k]), _ratio(sp[k])] for k in tp1]
        lines += [f"### {name}", "", *_table([key_label, "TP1", "TP2", "speedup"], rows), ""]
    return lines


def render_predictions_md(pred: dict) -> str:
    lines = [
        "# Predictions (a priori, committed before any GPU run)",
        "",
        "Every number below is generated by `tpprof/model.py` (`python -m tpprof predict`) from the "
        "constant sets listed at the end; nothing is hand-edited. The git tag `predictions-v1` marks the "
        "commit that fixed these predictions before the rental. Bands are the minimum and maximum over the "
        "optimistic, central and pessimistic constant sets.",
        "",
        "## Hypotheses",
        "",
    ]
    central = model.hypothesis_values(model.Constants(**pred["constants"]["central"]))
    rows = []
    for label, key, statement, kind in HYPOTHESES:
        band = pred["bands"][key]
        band_s = "none" if band is None else f"{_hyp_value(band[0], kind)}–{_hyp_value(band[1], kind)}"
        rows.append([label, statement, band_s, _hyp_value(central[key], kind)])
    lines += [*_table(["id", "statement", "band (lo–hi)", "central"], rows), ""]

    lines += ["## Decode step time (ms, context 1216)", "",
              "Per-step decode time at mean context 1216 (1024 prompt tokens plus the mean of the 64/320 "
              "output lengths); speedup = TP1 / TP2.", ""]
    lines += _tp_tables(pred["decode"], pred["ratios"]["decode_speedup"], "batch")

    lines += ["## Prefill (ms)", "",
              "Time to prefill one prompt of N tokens; speedup = TP1 / TP2.", ""]
    lines += _tp_tables(pred["prefill"], pred["ratios"]["prefill_speedup"], "N")

    lines += ["## KV cache capacity (tokens per engine)", "",
              "KV cache tokens per engine at `--gpu-memory-utilization 0.90`. DP2 runs two TP1-sized engines.",
              ""]
    kv_rows = [[n, _count(pred["kv"][n]["TP1"]), _count(pred["kv"][n]["TP2"]), _ratio(pred["kv"][n]["ratio"])]
               for n in SETS]
    lines += [*_table(["constants", "TP1", "TP2", "TP2 / TP1"], kv_rows), ""]

    lines += ["## Saturation output throughput (tok/s)", "",
              "Steady-state saturation output throughput for 1024 in / 256 out, whole config, with every engine "
              "at min(max_num_seqs 1024, KV tokens / 1280) running requests and no preemption.", ""]
    sat_rows = []
    for n in SETS:
        s = pred["saturation_tps"][n]
        sat_rows.append([n, _count(s["TP1"]), _count(s["TP2"]), _count(s["DP2"]), _ratio(pred["ratios"]["dp2_over_tp2_saturation"][n])])
    lines += [*_table(["constants", "TP1", "TP2", "DP2", "DP2 / TP2"], sat_rows), ""]

    lines += ["## Constants", "",
              "`d8` is D8's independent reference; unit tests pin the model to it. `central` differs from it "
              "only in the all-reduce bandwidth beta (260 GB/s measured on 2x H100).", ""]
    for name, consts in pred["constants"].items():
        rows = [[field, value if isinstance(value, str) else f"{value:.6g}", CONSTANT_UNITS.get(field, "")]
                for field, value in consts.items() if field != "name"]
        lines += [f"### {name}", "", *_table(["constant", "value", "unit"], rows), ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="tpprof predict", description="Write predictions.md from tpprof/model.py")
    parser.add_argument("--out", default="predictions.md", help="output path (default: predictions.md)")
    args = parser.parse_args(argv)
    out = pathlib.Path(args.out)
    out.write_text(render_predictions_md(model.predictions()), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
